#!/bin/bash
HOME_DIR=$(pwd)
if [ -z "$1" ]; then COUNT=1; else COUNT=$1; fi

cd $HOME_DIR/postgres/
./run_postgres.sh

cd $HOME_DIR/primary/
./build.sh
./run.sh

cd $HOME_DIR/secondary/
./build.sh
for (( i=1; i<=$COUNT; i++ ))
do
	./run.sh $i
done

cd $HOME_DIR/nginx/
./run.sh
